name: MineReact
main: com.evanpetousis.minereact.MineReact
version: 1.0.2-SNAPSHOT
author: Evan Petousis
commands:
  react:
    description: React to any message.
    usage: /react <reaction> <player> <index?>